name: Ubuntu Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu_build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson doxygen graphviz libcanberra-dev libdbus-glib-1-dev libglib2.0-dev libgtk-4-dev libadwaita-1-dev libluajit-5.1-dev libpci-dev libperl-dev libssl-dev python3-dev python3-cffi mono-devel desktop-file-utils gettext

      - name: Configure
        run: meson setup _builddir -Ddocs=enabled

      - name: Build
        run: meson compile -C _builddir

      - name: Build Docs
        run: meson compile -C _builddir doxygen

      - name: Test
        run: meson test -C _builddir

      - name: Install
        run: sudo meson install -C _builddir
